#!/usr/bin/env bash
set -e

SOURCE="${BASH_SOURCE[0]}"
if [[ -L $SOURCE ]]
then
    DIR=$(php -r "echo dirname(realpath('$SOURCE'));")
else
    DIR="$( cd "$( dirname "$SOURCE" )" && pwd )"
fi
php "$DIR/index.php" "$@"